version: "3.8"

services:
  backend:
    image: 641791054325.dkr.ecr.ap-south-1.amazonaws.com/sports-backend:latest
    container_name: sports_backend
    restart: always
    ports:
      - "5000:5000"

  frontend:
    image: 641791054325.dkr.ecr.ap-south-1.amazonaws.com/sports-frontend:latest
    container_name: sports_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
