name: CI/CD Deploy (ECR + EC2 + Trivy)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1
      BACKEND_IMAGE: sports-backend
      FRONTEND_IMAGE: sports-frontend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ---------- AWS Credentials ----------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # ---------- Login to ECR ----------
      - name: Login to AWS ECR
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV
          aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS --password-stdin \
            $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      # ---------- Build Backend Image ----------
      - name: Build Backend Image
        run: |
          docker build -t $BACKEND_IMAGE:latest app/backend

      # ---------- Trivy Scan Backend ----------
      - name: Trivy Scan Backend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: sports-backend:latest
          format: table
          severity: HIGH,CRITICAL
          vuln-type: os,library
          scanners: vuln
          ignore-unfixed: true
          exit-code: 1

      # ---------- Build Frontend Image ----------
      - name: Build Frontend Image
        run: |
          docker build \
            --build-arg REACT_APP_API_URL=http://${{ secrets.EC2_PUBLIC_IP }}:5000 \
            -t $FRONTEND_IMAGE:latest app/frontend

      # ---------- Trivy Scan Frontend ----------
      - name: Trivy Scan Frontend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: sports-frontend:latest
          format: table
          severity: HIGH,CRITICAL
          vuln-type: os,library
          scanners: vuln
          ignore-unfixed: true
          exit-code: 1

      # ---------- Push Images to ECR ----------
      - name: Push Images to ECR
        run: |
          docker tag $BACKEND_IMAGE:latest $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_IMAGE:latest
          docker tag $FRONTEND_IMAGE:latest $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_IMAGE:latest

          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_IMAGE:latest
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_IMAGE:latest

      # ---------- Setup SSH ----------
      - name: Setup SSH key for EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/devops-key
          chmod 600 ~/.ssh/devops-key
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      # ---------- Deploy on EC2 ----------
      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/devops-key ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            set -e
            cd /home/ubuntu
            
             # Login to AWS ECR on EC2 (token expires every 12 hours)
            aws ecr get-login-password --region ap-south-1 \
              | sudo docker login --username AWS --password-stdin \
              641791054325.dkr.ecr.ap-south-1.amazonaws.com

            # Pull latest images and restart containers
            sudo docker-compose pull
            sudo docker-compose up -d
          EOF
